name: Code Checks

on:
  push:
      paths-ignore:
          - 'docs/**'
  pull_request:
      paths-ignore:
          - 'docs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:

  cppcheck_2204:
    runs-on: ubuntu-22.04
    if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Requirements
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends cppcheck

      - name: Run cppcheck test
        run: ./scripts/cppcheck.sh

  other_checks:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Requirements
        run: |
            sudo apt-get install -y --no-install-recommends python3-pip
            sudo apt-get remove -y python3-jsonschema
            sudo pip3 install --break-system-packages cffconvert

      - name: Validate citation file
        run: |
            cffconvert --validate
            cffconvert -f bibtex
            cffconvert -f apalike
