name: mingw_w64 build

on:
  push:
      paths-ignore:
          - 'docs/**'
  pull_request:
      paths-ignore:
          - 'docs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:

  mingw_w64_build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache
        uses: actions/cache@v4
        id: cache
        with:
          path: |
                ${{ github.workspace }}/ccache.tar.gz
          key: ${{ runner.os }}-cache-mingw_w64-${{ github.run_id }}
          restore-keys: ${{ runner.os }}-cache-mingw_w64-

      - name: Build
        run: docker run -e CI -e TRAVIS_OS_NAME=linux -e BUILD_NAME=mingw_w64 -e WORK_DIR="$PWD" -v $PWD:$PWD ubuntu:22.04 $PWD/.github/workflows/mingw_w64/start.sh
